#docker-compose down
#rm docker-compose.yml
#nano docker-compose.yml
#docker-compose up -d

services:
  uptime-kuma:
    image: louislam/uptime-kuma
    restart: always
    ports:
     - "48080:80"
    volumes:
      - uptime_kuma_data:/app/data
    networks:
      - services_net

  vaultwarden:
    image: vaultwarden/server:latest
    restart: always
    ports:
     - "58080:80"
    volumes:
      - vaultwarden_data:/data
    networks:
      - services_net

networks:
  services_net:
    driver: bridge

volumes:
  uptime_kuma_data:
  vaultwarden_data:
 